# Generated by Django 4.2.16 on 2024-11-24 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the chat message', primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('CLIENT', 'Client'), ('PROVIDER', 'Service Provider')], help_text='Type of sender (Client or Service Provider)', max_length=10)),
                ('sender', models.UUIDField(help_text='UUID of the sender (either client_id or provider_id)')),
                ('message', models.TextField(help_text='Content of the chat message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the message was sent')),
                ('order', models.ForeignKey(help_text='Order associated with this chat', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='orders.orders')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['order', 'timestamp'], name='chat_chatme_order_i_3acaab_idx'), models.Index(fields=['sender', 'sender_type'], name='chat_chatme_sender_bafd4a_idx')],
            },
        ),
    ]
