# Generated by Django 4.2.16 on 2024-11-25 05:37

import chat.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.chat_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text Message'), ('IMAGE', 'Image Message')], default='TEXT', max_length=5),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='orders.orders'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PROVIDER', 'Service Provider')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
