# Generated by Django 4.2.16 on 2024-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_service', '0003_remove_subservice_is_default'),
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='sub_services',
            field=models.ManyToManyField(help_text='Services offered by this provider', related_name='providers', through='service_provider.ProviderService', to='sub_service.subservice'),
        ),
    ]
