# Generated by Django 4.2.16 on 2024-11-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0004_remove_providerservice_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for authentication', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for authentication', max_length=128, null=True),
        ),
    ]
