### Get single subservice
PATCH http://127.0.0.1:8000/services/{uuid}/subservices/{uuid}/
Authorization: Bearer your-auth-token-here
### Create new subservice


{
  "name": "nail polish2"
}
### Response - Success
HTTP/1.1 200 OK
Content-Type: application/json

{
  "status": true,
  "message": "Data retrieved successfully",
  "data": {
    "id": "8bb19428-a3ef-45a9-a3b7-b6f9d35c2e98",
    "name": "nail polish2",
    "main_service": "7ec4adff-0338-48d1-b963-17d26ac6a4c0",
    "main_service_name": "Salon",
    "providers_count": 0
  }
}

### Response - Not Found
HTTP/1.1 404 Not Found
Content-Type: application/json

{
  "status": false,
  "message": "Resource not found",
  "data": null
}