# Generated by Django 4.2.16 on 2024-11-09 07:31

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the client', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the client', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Client name must be at least 2 characters long'), django.core.validators.MaxLengthValidator(100, 'Client name cannot exceed 100 characters')])),
                ('email', models.EmailField(help_text="Client's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')])),
                ('password', models.CharField(help_text="Client's password (stored as a hashed value)", max_length=128, validators=[django.core.validators.MinLengthValidator(8, 'Password must be at least 8 characters long')])),
                ('mobile_number', models.CharField(help_text="Client's mobile number for contact", max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with 9 to 15 digits', regex='^\\+?1?\\d{9,15}$')])),
                ('street_address', models.CharField(help_text='Street address of the client', max_length=255)),
                ('city', models.CharField(help_text='City where the client resides', max_length=100)),
                ('state', models.CharField(help_text='State where the client resides', max_length=100)),
                ('postal_code', models.CharField(help_text="Client's postal code", max_length=20, validators=[django.core.validators.RegexValidator(message='Postal code must be between 5 and 10 digits', regex='^\\d{5,10}$')])),
                ('latitude', models.DecimalField(decimal_places=6, help_text="Latitude of the client's location", max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text="Longitude of the client's location", max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
    ]
