# Generated by Django 4.2.16 on 2024-11-09 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_number',
            field=models.CharField(help_text="Client's mobile number for contact", max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Full name of the client', max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Client name must be at least 2 characters long'), django.core.validators.MaxLengthValidator(20, 'Client name cannot exceed 20 characters')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(help_text="Client's password (stored as a hashed value)", max_length=128, validators=[django.core.validators.MinLengthValidator(5, 'Password must be at least 5 characters long')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(help_text="Client's postal code", max_length=6, validators=[django.core.validators.RegexValidator(message='Postal code must be exactly 6 digits', regex='^\\d{6}$')]),
        ),
    ]
    
