# Generated by Django 4.2.16 on 2024-11-09 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='is_default',
            field=models.BooleanField(default=True, help_text='Indicates if this is a default service available to all providers'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='name',
            field=models.CharField(help_text='Name of the specific service', max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
