# Generated by Django 4.2.16 on 2024-11-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_service', '0002_subservice_is_default_alter_subservice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='is_default',
        ),
    ]
