# Generated by Django 4.2.16 on 2024-11-17 10:21

from django.db import migrations, models
import sub_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_service', '0003_remove_subservice_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image representing the service (max 2MB)', null=True, upload_to='sub_service', validators=[sub_service.models.validate_image_size]),
        ),
    ]
