# Generated by Django 4.2.16 on 2024-11-16 07:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_client_mobile_number_alter_client_name_and_more'),
        ('service_provider', '0004_remove_providerservice_is_active_and_more'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the order', primary_key=True, serialize=False)),
                ('ordered_on', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the order was created')),
                ('scheduled_on', models.DateTimeField(help_text='Scheduled date and time for the service')),
                ('otp', models.CharField(help_text='6-character OTP for verification', max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the order', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total cost of the order', max_digits=10)),
                ('review', models.TextField(blank=True, help_text='Optional feedback from the client after order completion', null=True)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rating provided by the client (1 to 5)', null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)])),
                ('provider', models.ForeignKey(help_text='Service provider chosen for this order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='service_provider.serviceprovider')),
                ('service', models.ForeignKey(help_text='Main service chosen for this order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='service.service')),
                ('user', models.ForeignKey(help_text='Client who placed the order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the order status history entry', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], help_text='Status of the order at a particular time', max_length=20)),
                ('changed_on', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the status was changed')),
                ('order', models.ForeignKey(help_text='Order for which this status history entry is recorded', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the order item', primary_key=True, serialize=False)),
                ('order', models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orders')),
                ('provider_service', models.ForeignKey(help_text='Sub service ordered by the client', on_delete=django.db.models.deletion.CASCADE, to='service_provider.providerservice')),
            ],
        ),
    ]
