# Generated by Django 4.2.16 on 2024-11-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='client_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Latitude of the client's location", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='client_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Longitude of the client's location", max_digits=9, null=True),
        ),
    ]
