# Generated by Django 4.2.16 on 2024-12-08 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_client_latitude_orders_client_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Rating provided by the client (1 to 5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
