# Generated by Django 4.2.16 on 2024-11-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_client_latitude_orders_client_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='review',
            field=models.TextField(blank=True, help_text='Optional feedback from the client after order completion', max_length=500, null=True),
        ),
    ]
