# Generated by Django 4.2.16 on 2025-02-21 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_provider', '0005_serviceprovider_email_serviceprovider_password'),
        ('client', '0003_alter_client_latitude_alter_client_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_order', 'New Order'), ('order_accepted', 'Order Accepted'), ('order_rejected', 'Order Rejected'), ('order_completed', 'Order Completed')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.UUIDField()),
                ('recipient_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='client.client')),
                ('recipient_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='service_provider.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
